
volumes:
  todos-vol:

services:

  pgsql:
    image: postgres:12.11
    restart: always
    # environment: # REMOVED
    #   POSTGRES_PASSWORD: pwd # Here # REMOVED
    #   POSTGRES_USER: usr # Here # REMOVED
    #   POSTGRES_DB: todos # Here # REMOVED
    env_file:
      - .env
    volumes:
      - todos-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432      

  python: # Can change name here
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    depends_on:
     - pgsql
      # using port 80 for convenience so we can access localhost directly without specifying the port
    ports:
      - 8000:8000
    # the Flask app' code will go into the `app` folder of your project and be mapped to `/usr/src/app` in the container
    volumes:
      - ./app:/usr/src/app
