version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - pgsql
    environment:
      - FLASK_APP=app:create_app # This could be app only
      - FLASK_RUN_HOST=0.0.0.0

  pgsql:
    image: postgres:12.11
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:


